export const SET_DEFAULT_REPOSITORIES =
  'ALL_REPOSITORIES_PAGE/SET_DEFAULT_REPOSITORIES';
export const GET_PAGE = 'ALL_REPOSITORIES_PAGE/GET_PAGE_CHANGE';
export const GET_NAME_SEARCH = 'ALL_REPOSITORIES_PAGE/GET_NAME_SEARCH';
export const SET_LOADED = 'ALL_REPOSITORIES_PAGE/SET_LOADED';
export const SET_FULL_NAMES = 'ALL_REPOSITORIES_PAGE/SET_FULL_NAMES';
export const SET_LIST_KEYS = 'ALL_REPOSITORIES_PAGE/SET_LIST_KEYS';
export const SET_COMMITS_DATE = 'ALL_REPOSITORIES_PAGE/SET_COMMITS_DATE';
