export const SET_DEFAULT_REPOSITORIES =
  'ALL_REPOSITORIES_PAGE_SET_DEFAULT_REPOSITORIES';
export const GET_PAGE = 'ALL_REPOSITORIES_PAGE_GET_PAGE_CHANGE';
export const GET_NAME_SEARCH = 'ALL_REPOSITORIES_PAGE_GET_NAME_SEARCH';
export const SET_LOADED = 'ALL_REPOSITORIES_PAGE_SET_LOADED';
export const SET_FULL_NAMES = 'ALL_REPOSITORIES_PAGE_SET_FULL_NAMES';
export const SET_COMMITS_LIST = 'ALL_REPOSITORIES_PAGE_SET_COMMITS_LIST';
