export const SET_DEFAULT_REPOSITORIES = 'SET_DEFAULT_REPOSITORIES';
export const GET_PAGE = 'GET_PAGE_CHANGE';
export const GET_NAME_SEARCH = 'GET_NAME_SEARCH';
export const SET_LOADED = 'SET_LOADED';
export const SET_FULL_NAMES = 'SET_LOADED_COMMITS';
export const SET_COMMITS_LIST = 'SET_COMMITS_LIST';
export const SET_LOADED_COMMITS = 'SET_LOADED_COMMITS';
