export const SET_REPOSITORY_INFO = 'USER_CARD_PAGE/SET_REPOSITORY_INFO';
export const SET_REPOSITORY_COMMITS = 'USER_CARD_PAGE/SET_REPOSITORY_COMMITS';
export const SET_REPOSITORY_LANGUAGES =
  'USER_CARD_PAGE/SET_REPOSITORY_LANGUAGES';
export const SET_REPOSITORY_CONTRIBUTORS =
  'USER_CARD_PAGE/SET_REPOSITORY_CONTRIBUTORS';
export const SET_LOADED_CARD = 'USER_CARD_PAGE/SET_LOADED_CARD';
export const USER_CARD_PAGE_SET_REPOSITORY_NAME =
  'USER_CARD_PAGE/SET_REPOSITORY_NAME';
