export const SET_REPOSITORY_INFO = 'SET_REPOSITORY_INFO';
export const SET_REPOSITORY_COMMITS = 'SET_REPOSITORY_COMMITS';
export const SET_REPOSITORY_LANGUAGES = 'SET_REPOSITORY_LANGUAGES';
export const SET_REPOSITORY_CONTRIBUTORS = 'SET_REPOSITORY_CONTRIBUTORS'